import type { ModelInfo, ProviderInfo } from '@/services/providers/types';

export const PROVIDER_LIST: ProviderInfo[] = [
  { id: 'openai', label: 'OpenAI' },
  { id: 'anthropic', label: 'Anthropic' },
];

export const FALLBACK_MODEL_LIST: ModelInfo[] = [
  {
    id: 'openai:gpt-5.2',
    label: 'GPT-5.2',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 1,
  },
  {
    id: 'openai:gpt-5.2:minimal',
    baseModelId: 'openai:gpt-5.2',
    label: 'GPT-5.2 Minimal',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 2,
    providerOptions: { openai: { reasoningEffort: 'low' } },
    maxOutputTokens: 4000,
  },
  {
    id: 'openai:gpt-5.2:low',
    baseModelId: 'openai:gpt-5.2',
    label: 'GPT-5.2 Low',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 3,
    providerOptions: { openai: { reasoningEffort: 'low' } },
  },
  {
    id: 'openai:gpt-5.2:medium',
    baseModelId: 'openai:gpt-5.2',
    label: 'GPT-5.2 Medium',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 4,
    providerOptions: { openai: { reasoningEffort: 'medium' } },
  },
  {
    id: 'openai:gpt-5.2:high',
    baseModelId: 'openai:gpt-5.2',
    label: 'GPT-5.2 High',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 5,
    providerOptions: { openai: { reasoningEffort: 'high' } },
  },
  {
    id: 'openai:gpt-5.2:extra-high',
    baseModelId: 'openai:gpt-5.2',
    label: 'GPT-5.2 Extra High',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 6,
    providerOptions: { openai: { reasoningEffort: 'high' } },
    maxOutputTokens: 100000,
  },
  {
    id: 'openai:gpt-5-mini',
    label: 'GPT-5 Mini',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 10,
  },
  {
    id: 'openai:gpt-5-mini:minimal',
    baseModelId: 'openai:gpt-5-mini',
    label: 'GPT-5 Mini Minimal',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 11,
    providerOptions: { openai: { reasoningEffort: 'low' } },
    maxOutputTokens: 4000,
  },
  {
    id: 'openai:gpt-5-mini:low',
    baseModelId: 'openai:gpt-5-mini',
    label: 'GPT-5 Mini Low',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 12,
    providerOptions: { openai: { reasoningEffort: 'low' } },
  },
  {
    id: 'openai:gpt-5-mini:medium',
    baseModelId: 'openai:gpt-5-mini',
    label: 'GPT-5 Mini Medium',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 13,
    providerOptions: { openai: { reasoningEffort: 'medium' } },
  },
  {
    id: 'openai:gpt-5-mini:high',
    baseModelId: 'openai:gpt-5-mini',
    label: 'GPT-5 Mini High',
    provider: 'openai',
    providerLabel: 'OpenAI',
    sortOrder: 14,
    providerOptions: { openai: { reasoningEffort: 'high' } },
  },
  {
    id: 'anthropic:claude-opus-4-6',
    label: 'Claude Opus 4.6',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 18,
  },
  {
    id: 'anthropic:claude-opus-4-6:thinking-low',
    baseModelId: 'anthropic:claude-opus-4-6',
    label: 'Claude Opus 4.6 Thinking Low',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 19,
    providerOptions: { anthropic: { thinking: { type: 'enabled', budgetTokens: 8000 } } },
  },
  {
    id: 'anthropic:claude-opus-4-6:thinking-medium',
    baseModelId: 'anthropic:claude-opus-4-6',
    label: 'Claude Opus 4.6 Thinking Medium',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 20,
    providerOptions: { anthropic: { thinking: { type: 'enabled', budgetTokens: 16000 } } },
  },
  {
    id: 'anthropic:claude-opus-4-6:thinking-high',
    baseModelId: 'anthropic:claude-opus-4-6',
    label: 'Claude Opus 4.6 Thinking High',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 21,
    providerOptions: { anthropic: { thinking: { type: 'enabled', budgetTokens: 32000 } } },
  },
  {
    id: 'anthropic:claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 22,
  },
  {
    id: 'anthropic:claude-sonnet-4-6:thinking-low',
    baseModelId: 'anthropic:claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6 Thinking Low',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 23,
    providerOptions: { anthropic: { thinking: { type: 'enabled', budgetTokens: 8000 } } },
  },
  {
    id: 'anthropic:claude-sonnet-4-6:thinking-medium',
    baseModelId: 'anthropic:claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6 Thinking Medium',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 24,
    providerOptions: { anthropic: { thinking: { type: 'enabled', budgetTokens: 16000 } } },
  },
  {
    id: 'anthropic:claude-sonnet-4-6:thinking-high',
    baseModelId: 'anthropic:claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6 Thinking High',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 25,
    providerOptions: { anthropic: { thinking: { type: 'enabled', budgetTokens: 32000 } } },
  },
  {
    id: 'anthropic:claude-haiku-4-5',
    label: 'Claude Haiku 4.5',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 30,
  },
  {
    id: 'anthropic:claude-haiku-4-5:thinking-low',
    baseModelId: 'anthropic:claude-haiku-4-5',
    label: 'Claude Haiku 4.5 Thinking Low',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 31,
    providerOptions: { anthropic: { thinking: { type: 'enabled', budgetTokens: 4000 } } },
  },
  {
    id: 'anthropic:claude-haiku-4-5:thinking-medium',
    baseModelId: 'anthropic:claude-haiku-4-5',
    label: 'Claude Haiku 4.5 Thinking Medium',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 32,
    providerOptions: { anthropic: { thinking: { type: 'enabled', budgetTokens: 8000 } } },
  },
  {
    id: 'anthropic:claude-haiku-4-5:thinking-high',
    baseModelId: 'anthropic:claude-haiku-4-5',
    label: 'Claude Haiku 4.5 Thinking High',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    sortOrder: 33,
    providerOptions: { anthropic: { thinking: { type: 'enabled', budgetTokens: 16000 } } },
  },
];
